// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCPPSDRKChSENNE0WYfB816qtAsSCK91M',
    appId: '1:728071700916:web:7ba2a7a14ec46d913972e1',
    messagingSenderId: '728071700916',
    projectId: 'kigali-directory-62c4b',
    authDomain: 'kigali-directory-62c4b.firebaseapp.com',
    storageBucket: 'kigali-directory-62c4b.firebasestorage.app',
    measurementId: 'G-CY5477NV30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs6vxhZ8jc3sm3izx-1TABxN66XEpxXK8',
    appId: '1:728071700916:android:18df13c24e430fdb3972e1',
    messagingSenderId: '728071700916',
    projectId: 'kigali-directory-62c4b',
    storageBucket: 'kigali-directory-62c4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD13G2iE1fuyyTB3K5ubW88goxRPhqMVY8',
    appId: '1:728071700916:ios:427359e8cce205ca3972e1',
    messagingSenderId: '728071700916',
    projectId: 'kigali-directory-62c4b',
    storageBucket: 'kigali-directory-62c4b.firebasestorage.app',
    iosBundleId: 'com.example.kigaliDirectory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD13G2iE1fuyyTB3K5ubW88goxRPhqMVY8',
    appId: '1:728071700916:ios:427359e8cce205ca3972e1',
    messagingSenderId: '728071700916',
    projectId: 'kigali-directory-62c4b',
    storageBucket: 'kigali-directory-62c4b.firebasestorage.app',
    iosBundleId: 'com.example.kigaliDirectory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCPPSDRKChSENNE0WYfB816qtAsSCK91M',
    appId: '1:728071700916:web:f842c93d7969b73d3972e1',
    messagingSenderId: '728071700916',
    projectId: 'kigali-directory-62c4b',
    authDomain: 'kigali-directory-62c4b.firebaseapp.com',
    storageBucket: 'kigali-directory-62c4b.firebasestorage.app',
    measurementId: 'G-8VQ3944XBS',
  );
}
